#!/usr/bin/env bash

docker build runner -t runner
docker run --privileged --rm -v /dev:/dev:ro -v "$PWD":/runner -w /runner -e ALPINE_BRANCH="${ALPINE_BRANCH:-edge}" -e ALPINE_MIRROR="${ALPINE_MIRROR:-http://dl-cdn.alpinelinux.org/alpine}" -e ARCH="${ARCH:-armhf}" runner ./make-image
